# Generated by Django 5.0.6 on 2024-07-02 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_projectpage_client_name_projectpage_completion_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Project",
        ),
    ]
