# Generated by Django 5.0.6 on 2024-07-03 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_package_packagesummary"),
    ]

    operations = [
        migrations.AddField(
            model_name="package",
            name="color_code",
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
